### ISSUE TITLE
mail set password at runtime or on init (read it for `/secrets/smtp.txt`)

### ISSUE THREAD

**Issue by IbrahimOuhamou** [jetzig-framework/jetzig#105]
is there a way to set the email at runtime?

or do we just mark it as `var` in the config then edit it in `main()` or `init()`?

**Comment by bobf** [comment]
@IbrahimOuhamou I've been meaning to fix this for ages, thanks for the extra push. : )

You can now set the following environment variables to configure SMTP:
```
JETZIG_SMTP_PORT
JETZIG_SMTP_ENCRYPTION
JETZIG_SMTP_HOST
JETZIG_SMTP_USERNAME
JETZIG_SMTP_PASSWORD
```

`JETZIG_SMTP_ENCRYPTION` must be one of:
```
insecure
none
tls
start_tls
```

Hopefully this solution works for you.

**Comment by IbrahimOuhamou** [comment]
@bobf well, thanks ❤
