### ISSUE TITLE
Getting an `httpz BodyTooBig` error prevents `127.0.0.1:8080` from loading

### ISSUE THREAD

**Issue by mitteneer** [jetzig-framework/jetzig#126]
1. Run `jetzig server`
2. Upload a large enough file to get a `BodyTooBig` error from `httpz`
3. `127.0.0.1:8080` never loads, even after stopping and rerunning `jetzig server`

My code:
```
pub fn post(request: *jetzig.Request) !jetzig.View {
    const Scrobble = struct {
        track: []u8,
        artist: []u8,
        album: []u8,
        date: i64,
    };

    const lastfm = struct {
        username: []u8,
        scrobbles: []Scrobble,
    };

    var root = try request.data(.object);

    if (try request.file("upload")) |file| {
        const parsed = try std.json.parseFromSlice(lastfm, request.allocator, file.content, .{});

        const history = parsed.value;

        for (history.scrobbles) |scrobble| {
            const song_hash: u64 = std.hash.Fnv1a_64.hash(scrobble.track) % 99999989;
            std.debug.print("{d}\n", .{song_hash});

        }
    }

    return request.render(.created);
}
```

Example file:
[lastfmstats-VAOTM(1).json](https://github.com/user-attachments/files/17940990/lastfmstats-VAOTM.1.json)

For what it's worth, I've set `pub const max_bytes_request_body: usize = std.math.pow(usize, 2, 32);` in `main.zig`, which may not be the corresponding configuration value, but I wasn't really expecting a `BodyTooBig` error after setting that.

**Comment by bobf** [comment]
@mitteneer Really sorry it took so long to get to this - the `max_bytes_request_body` const was actually unused - I never migrated it across when we switched from `std.http.Server` to `http.zig`.

I've fixed it in this PR: https://github.com/jetzig-framework/jetzig/pull/130

I tested locally by submitting a gigantic blog post, got a failure, then modified that setting then was able to submit the post without issue so I think it should solve your issue.

Let me know how it goes !

**Comment by mitteneer** [comment]
@bobf Thank you! Not sure if it's related, but I'm getting a Connection Reset error when I run `jetzig server` now, and nothing comes up in the terminal. If I run `zig build run` I get a slightly more specific, but not particularly helpful error
```
error: the following command terminated unexpectedly:
/home/swebb/Source/zuletzt/zig-out/bin/zuletzt 
Build Summary: 14/16 steps succeeded; 1 failed
run transitive failure
└─ run zuletzt failure
error: the following build command failed with exit code 1:
/home/swebb/Source/zuletzt/.zig-cache/o/9ac3f4ffa6b6b093c4228b1db1e7b2f5/build /home/swebb/.zvm/master/zig /home/swebb/.zvm/master/lib /home/swebb/Source/zuletzt /home/swebb/Source/zuletzt/.zig-cache /home/swebb/.cache/zig --seed 0xc47b5fb2 -Z316080db31fa7fde run
```
I did do some editing prior to testing, but I don't know what I might have done to cause an error so esoteric

**Comment by z1fire** [comment]
try deleting your zig cache and rebuilding maybe?

**Comment by mitteneer** [comment]
@z1fire No change, deleted both `~/.cache/zig/` and `zuletzt/.zig-cache/`

**Comment by z1fire** [comment]
@mitteneer what kinds of changes did you do before testing

**Comment by mitteneer** [comment]
I rolled back my database tables, changed a table, migrated/reflected, and made some edits to a job. You can see the code [here](https://git.sawebb.xyz/mitteneer/zuletzt/src/branch/testing)

**Comment by z1fire** [comment]
And it worked before those changes?

**Comment by mitteneer** [comment]
I didn't immediately test the new version of jetzig, but it was working previous to the edits I made, which I know doesn't help much unfortunately, except to say that it worked previously.

**Comment by z1fire** [comment]
@mitteneer I see in the testing branch you importing static and zmd but I don't see them in either the build.zig or the zon file.

**Comment by bobf** [comment]
@mitteneer This seems to be because you've set the maximum request body size to 2**32, which is 4.3G. Jetzig's backend (http.zig) is pre-allocating space for that request body size for each worker thread, so it's trying to allocate CPU count x 4.3G. On my machine that's around 34G.

Probably your process is getting killed by your operating system. Try setting the maximum body size to something a bit smaller. If you actually do need 4.3G let me know and I'll have a think about how we might be able to support that.

I set the value to 2**24 which is around 16M:
```zig
    pub const max_bytes_request_body: usize = std.math.pow(usize, 2, 24);
```
Server loads fine and I'm able to load it in my browser without issues.

**Comment by mitteneer** [comment]
Ah, okay. I had it at 2**32 originally to test `max_bytes_request_body` and forgot to switch it back. It works now, thanks for all the help!

**Comment by bobf** [comment]
@mitteneer No problem ! :+1:
