### ISSUE TITLE
Maybe start a jetzig discord channel

### ISSUE THREAD

**Issue by z1fire** [jetzig-framework/jetzig#2]
I suggest starting a jetzig discord channel for those interested in keeping up and talking and helping with jetzig.

**Comment by bobf** [comment]
@z1fire Hi, sorry, covid happened - I'm back now. I'm a total newbie at Discord but I am very much open to the idea of building a community. Can you tell me what is the typical way to do this ? Do I create my own server, or a channel on an existing server ? I'm in a couple of Zig servers.

Any advice is welcome !

**Comment by z1fire** [comment]
@bobf Hey that is totally fine, more important to get better lol. Only my personal opinion but create your own server. Zap has its own and it's nice to talk zap things in it. Just put a couple of channels in it for general talk, maybe a brainstorming channel, and definitely a showcase channel.

**Comment by bobf** [comment]
All right, here goes !

https://discord.gg/8bKHkxjM

I hope I did it right. : )

Thanks for the suggestion, let me know if I messed it up.

**Comment by z1fire** [comment]
Looks like a server to me lol. Just joined. Make sure to add the link to the repo readme
