### ISSUE TITLE
AccessDenied error on windows 10

### ISSUE THREAD

**Issue by sibkit** [jetzig-framework/jetzig#66]
I'm trying to run an example after jetzig init. I get the error:

-------------------------------------------------------------------
You may only use the C/C++ Extension for Visual Studio Code
with Visual Studio Code, Visual Studio or Visual Studio for Mac
software to help you develop and test your applications.
-------------------------------------------------------------------
Loaded 'D:\Dev\Zig\Projects\test_jetzig\zig-out\bin\test_jetzig.exe'. Symbols loaded.
Loaded 'C:\Windows\System32\ntdll.dll'. 
Loaded 'C:\Windows\System32\kernel32.dll'. 
Loaded 'C:\Windows\System32\KernelBase.dll'. 
Loaded 'C:\Windows\System32\apphelp.dll'. 
Loaded 'C:\Windows\System32\ws2_32.dll'. 
Loaded 'C:\Windows\System32\rpcrt4.dll'. 
Loaded 'C:\Windows\System32\crypt32.dll'. 
Loaded 'C:\Windows\System32\ucrtbase.dll'. 
Loaded 'C:\Windows\System32\advapi32.dll'. 
Loaded 'C:\Windows\System32\msvcrt.dll'. 
Loaded 'C:\Windows\System32\sechost.dll'. 
Loaded 'C:\Windows\System32\bcrypt.dll'. 
Loaded 'C:\Windows\System32\cryptbase.dll'. 
Loaded 'C:\Windows\System32\bcryptprimitives.dll'. 
 WARN [2024-05-12 02:04:17] Running in development mode, using auto-generated cookie encryption key: lj2kD?RKQ?dv1R1Y?XFBYpfAO4MpeN2n
 WARN [2024-05-12 02:04:17] Run `jetzig generate secret` and set `JETZIG_SECRET` to remove this warning.
 INFO [2024-05-12 02:04:17] [worker-2] Job worker started.
 INFO [2024-05-12 02:04:17] [worker-3] Job worker started.
 INFO [2024-05-12 02:04:17] [worker-0] Job worker started.
 INFO [2024-05-12 02:04:17] [worker-1] Job worker started.
Loaded 'C:\Windows\System32\mswsock.dll'. 
ERROR [2024-05-12 02:04:17] Encountered error: error.AccessDenied
Exiting.

The program '[13940] test_jetzig.exe' has exited with code 1 (0x1).

I think this is because port 8080 is busy, how can I change the port?

**Comment by sibkit** [comment]
I found! 
$ zig build install
$ zig-out/bin/myapp -p 8100

**Comment by bobf** [comment]
@sibkit Glad you got the issue resolved, feel free to reach out if you have any more problems.
