### ISSUE TITLE
Bug on windows with subfolders in public folder

### ISSUE THREAD

**Issue by drsneed** [jetzig-framework/jetzig#87]
Hello,
I discovered that on Windows, Jetzig fails to serve any files that are in subfolders inside the public folder.
This is because [line 605 in jetzig/http/Server.zig](https://github.com/jetzig-framework/jetzig/blob/179b5e77c3a79ca3506e318e91e8e1ade698ba30/src/jetzig/http/Server.zig#L605) is comparing a windows path ("foo\bar") with a posix path ("foo/bar").

I can submit a pull request but I'm not sure if my solution is the best, I'm just replacing "\\" with "/" before the comparison.
Thanks,
- Dustin

**Comment by bobf** [comment]
@drsneed Thanks for reporting. Normalising paths on `/` is fine (i.e. replacing `\` with `/`) in most cases I think (some edge cases but oh well). If you want to submit a PR I will definitely merge it. : )

**Comment by drsneed** [comment]
Thanks I submitted one.
