### ISSUE TITLE
Consider adding `zig-package` tag to the sidebar blurb

### ISSUE THREAD

**Issue by mnemnion** [jetzig-framework/jetzig#99]
That's what [Zigistry](https://zigistry.dev/) uses to find packages, and other aggregators can piggyback on the convention as well.

**Comment by bobf** [comment]
@mnemnion Nice idea - have added to Jetzig, Zmpl, JetKV, and Zmd. I'll add to JetQuery once it's ready for use. Thanks for the suggestion. :+1:

**Comment by mnemnion** [comment]
You're welcome. ^_^
